export const SECRET_PATTERNS = {
  "General API Key": /\bAPI\s*Key\s*[:=]?\s*['"]?([A-Za-z0-9_-]{32,})['"]?/gi,
  "API Token": /\bAPI\s*Token\s*[:=]?\s*['"]?([A-Za-z0-9_-]{32,})['"]?/gi,
  "AWS Access Key ID": /AWS\s*Access\s*Key\s*ID\s*[:=]?\s*['"]?([AIAZ0-9]{20})['"]?/gi,
  "AWS Secret Access Key": /AWS\s*Secret\s*Access\s*Key\s*[:=]?\s*['"]?([A-Za-z0-9/+=]{40})['"]?/gi,
  "GitHub Token": /GitHub\s*Token\s*[:=]?\s*['"]?(ghp_[A-Za-z0-9]{36})['"]?/gi,
  "GitHub Client Secret": /GitHub\s*Client\s*Secret\s*[:=]?\s*['"]?([A-Za-z0-9]{40})['"]?/gi,
  "Google API Key": /Google\s*API\s*Key\s*[:=]?\s*['"]?(AIza[A-Za-z0-9_-]{35})['"]?/gi,
  "Firebase API Key": /Firebase\s*API\s*Key\s*[:=]?\s*['"]?(AIza[A-Za-z0-9_-]{35})['"]?/gi,
  "Stripe Live Token": /sk_live_[A-Za-z0-9]{24}/gi,
  "Stripe Test Token": /sk_test_[A-Za-z0-9]{24}/gi,
  "Twilio API Key": /SK[A-Za-z0-9]{32}/gi,
  "Twilio Account SID": /AC[A-Za-z0-9]{32}/gi,
  "Slack API Token": /xox[bpars]-[A-Za-z0-9-]{10,48}/gi,
  "Mailgun API Key": /key-[A-Za-z0-9]{32}/gi,
  "SendGrid API Key": /SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}/gi,
  "Cloudflare API Key": /[A-Za-z0-9]{37}/gi,
  "Heroku API Key": /[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}/gi,
  "DigitalOcean API Key": /dop_v1_[A-Za-z0-9]{64}/gi,
  "Azure API Key": /[A-Za-z0-9]{40}/gi,
  "Discord Bot Token": /[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}/gi,
  "Discord Webhook": /https:\/\/discord(?:app)?\.com\/api\/webhooks\/\d+\/[\w-]+/gi,
  "Telegram Bot Token": /\d{8,10}:[A-Za-z0-9_-]{35}/gi,
  "Facebook Access Token": /EAA[A-Za-z0-9]{100,}/gi,
  "Instagram Access Token": /IGQV[A-Za-z0-9_-]{100,}/gi,
  "Twitter Bearer Token": /AAAAAAAAAAAAAAAAAAAAAA[A-Za-z0-9%]{50,}/gi,
  "LinkedIn Access Token": /AQV[A-Za-z0-9_-]{50,}/gi,
  "PayPal Client ID": /A[A-Za-z0-9_-]{80}/gi,
  "Square Access Token": /sq0atp-[A-Za-z0-9_-]{22}/gi,
  "Square Application ID": /sq0idp-[A-Za-z0-9_-]{43}/gi,
  "Shopify Access Token": /shpat_[A-Za-z0-9]{32}/gi,
  "Shopify Private App Password": /shppa_[A-Za-z0-9]{32}/gi,
  "Hardcoded API Key": /api_key\s*[:=]\s*['"]([a-zA-Z0-9_.-]{20,})['"]?/gi,
  "Hardcoded Secret": /secret\s*[:=]\s*['"]([a-zA-Z0-9_.-]{20,})['"]?/gi,
  "Hardcoded Password": /password\s*[:=]\s*['"]([a-zA-Z0-9_.-]{8,})['"]?/gi,
  "Hardcoded Token": /token\s*[:=]\s*['"]([a-zA-Z0-9_.-]{32,})['"]?/gi,
  "Access Token": /access_token\s*[:=]\s*['"]([a-zA-Z0-9_.-]{32,})['"]?/gi,
  "Auth Token": /auth_token\s*[:=]\s*['"]([a-zA-Z0-9_.-]{32,})['"]?/gi,
  "Bearer Token": /Bearer\s+([A-Za-z0-9_.-]{20,})/gi,
  "JWT Token": /eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/gi,
  "Private Key": /-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----[\s\S]*?-----END\s+(?:RSA\s+)?PRIVATE\s+KEY-----/gi,
  "SSH Private Key": /-----BEGIN\s+OPENSSH\s+PRIVATE\s+KEY-----[\s\S]*?-----END\s+OPENSSH\s+PRIVATE\s+KEY-----/gi,
  "Database URL": /(mongodb|mysql|postgresql|postgres):\/\/[^\s'"]+/gi,
  "Connection String": /(?:Server|Data Source|Host)=[^;'"]+;.*(?:Password|Pwd)=[^;'"]+/gi,
  Email: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/gi,
  "Phone Number": /[+]?[1-9]?[0-9]{7,15}/gi,
  "Credit Card":
    /\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3[0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\b/gi,
  "IP Address": /\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b/gi,
  "URL with Credentials": /https?:\/\/[^/\s:]+:[^/\s@]+@[^\s'"]+/gi,
}

export const SEVERITY_MAP: Record<string, "low" | "medium" | "high" | "critical"> = {
  "AWS Access Key ID": "critical",
  "AWS Secret Access Key": "critical",
  "GitHub Token": "high",
  "GitHub Client Secret": "high",
  "Google API Key": "high",
  "Firebase API Key": "high",
  "Stripe Live Token": "critical",
  "Stripe Test Token": "critical",
  "Twilio API Key": "medium",
  "Twilio Account SID": "medium",
  "Slack API Token": "high",
  "Mailgun API Key": "high",
  "SendGrid API Key": "high",
  "Cloudflare API Key": "medium",
  "Heroku API Key": "medium",
  "DigitalOcean API Key": "medium",
  "Azure API Key": "medium",
  "Discord Bot Token": "high",
  "Discord Webhook": "high",
  "Telegram Bot Token": "high",
  "Facebook Access Token": "high",
  "Instagram Access Token": "high",
  "Twitter Bearer Token": "high",
  "LinkedIn Access Token": "high",
  "PayPal Client ID": "medium",
  "Square Access Token": "medium",
  "Square Application ID": "medium",
  "Shopify Access Token": "medium",
  "Shopify Private App Password": "medium",
  "Hardcoded Password": "high",
  "General API Key": "medium",
  "API Token": "medium",
  "Hardcoded API Key": "medium",
  "Hardcoded Secret": "medium",
  "Hardcoded Token": "medium",
  "Access Token": "medium",
  "Auth Token": "medium",
  "Bearer Token": "medium",
  "JWT Token": "medium",
  "Private Key": "critical",
  "SSH Private Key": "critical",
  "Database URL": "medium",
  "Connection String": "high",
  Email: "low",
  "Phone Number": "low",
  "Credit Card": "critical",
  "IP Address": "low",
  "URL with Credentials": "high",
}
