name: Deploy Web App

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.11'
          channels: conda-forge,defaults
          activate-environment: jsninja
          use-mamba: true

      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            conda-
          
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda env update --file environment.yml --name jsninja
          python -m pip install --upgrade pip
          pip install -e .
          pip install ghp-import

      - name: Build static files
        run: |
          mkdir -p build
          cp -r jsninja/web/static build/
          cp jsninja/web/templates/index.html build/
          # Replace server-side template variables
          sed -i 's|{{ request.url_for("static", path="\([^"]*\)") }}|/static/\1|g' build/index.html
          # Create .nojekyll to prevent Jekyll processing
          touch build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          enable_jekyll: false