name: Deploy Web App

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ghp-import

      - name: Build static files
        run: |
          mkdir -p build
          cp -r jsninja/web/static build/
          cp jsninja/web/templates/index.html build/
          # Replace server-side template variables
          sed -i 's|{{ request.url_for("static", path="\([^"]*\)") }}|/static/\1|g' build/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true